WITH RECURSIVE G (ID, PARENT_ID, GENERATION) AS (
    SELECT ID, PARENT_ID, 1
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL 
    
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA
    INNER JOIN G ON G.ID = ECOLI_DATA.PARENT_ID
)

SELECT COUNT(G.ID) AS COUNT, GENERATION
FROM G
LEFT JOIN ECOLI_DATA as child ON child.PARENT_ID = G.ID
WHERE child.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC

